### ISSUE TITLE
 cross compile the source question

### ISSUE THREAD

**Issue by TonyHo722** [Xilinx/defect-detect#1]
I want to build the source and update to KV260 board with my modification.
I read the REAMME as below.
Does it with link or more detail procedure for "how to  build the cross-compilation SDK"?
- I had google it, but I can't find any infomation I can use.
Any comment is welcome.

```
1. Refer to the K260 SOM Starter Kit Tutorial to build the cross-compilation SDK, and install it to the path you choose or default. Suppose it's SDKPATH.

2. Run "./build.sh ${SDKPATH}" in the source code folder of current application, to build the application.

3. The build process in  will produce a rpm package DefectDetect-2.0.1-1.aarch64.rpm under build/, upload to the board, and run "rpm -ivh --force ./DefectDetect-2.0.1-1.aarch64.rpm" to install updates.
```

**Comment by TonyHo722** [comment]
I am trying to update the code and build it by using petalinux-build.
I expect I can create a boot image and I can get the *.so from the boot image in SD card.
but it take time and to many procedure to get the *.so.
I want to find out a better way to do it like use rpm.

**Comment by JoshSu0** [comment]
As the section "Build the SDK" instructions described in link below, a shell script ("images/linux/sdk.sh") used for creating the cross-compilation SDK environment can be created by command "petalinux-build --sdk". 
After executing the script, the SDK can be installed into a specific path, and which path is named "$SDKPATH".
The application can be cross built by build.sh together with "$SDKPATH" path.

https://xilinx.github.io/kria-apps-docs/main/build/html/docs/build_petalinux.html

**Comment by saketxilinx** [comment]
Hello,
You can either try with RPM which is the most efficient way to alter the code and push the binaries where only a one-time Petalinux build is required.

Another way is, In Petalinux you can enable the application and build it using the "petalinux-build -c  defect-detect -x do_compile  -f" command. modify if required and build it again using the same command. The binaries will be available in the {TEMP}/work/cortexa72-cortexa53-xilinx-linux/defect-detect/1.0-r0/build/. You can take the binary and push it to the Xilinx platform and run the app.

**Comment by TonyHo722** [comment]
@JoshSu0,

The link you provide i want I need.
I can build application by SDK now.
Thank you.


@saketxilinx,
I had try it, it is work.
I perfer use SDK to build RPM package.
Thank for your comment, too.
